apiVersion: v1
kind: Secret
metadata:
  name: {{ include "textreaderrpi.fullname" . }}-secret
  labels:
    {{- include "textreaderrpi.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_USER: {{ .Values.database.user | quote }}
  DATABASE_PASSWORD: {{ required "database.password must be set (--set database.password=...)" .Values.database.password | quote }}

