{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "textreaderrpi.fullname" . }}-sa
  labels:
    {{- include "textreaderrpi.labels" . | nindent 4 }}
{{- end }}

